version: '3'
services:
  pretalx:
    image: pretalx/standalone:latest
    container_name: pretalx
    restart: unless-stopped
    depends_on:
      - redis
      - db
    ports:
      - "127.0.0.1:8346:80"
    volumes:
      - ./conf/pretalx.cfg:/etc/pretalx/pretalx.cfg:ro
      - pretalx-data:/data
  db:
    image: mysql:latest
    container_name: pretalx-db
    restart: unless-stopped
    volumes:
      - pretalx-db:/var/lib/mysql
      - ./mysql/scrpts/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: pretalx
      MYSQL_USER: pretalx
      MYSQL_PASSWORD: veryunsecureplschange
      MYSQL_ROOT_PASSWORD: "root"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redis:
    image: redis:latest
    container_name: pretalx-redis
    restart: unless-stopped
    volumes:
      - pretalx-redis:/data

  pretix:
    image: pretix/standalone:stable
    sysctls:
      - net.core.somaxconn=4096
    container_name: pretix
    restart: unless-stopped
    depends_on:
      - redis-pretix
      - db-pretix
    ports:
      - "127.0.0.1:8345:80"
    volumes:
      - ./conf/pretix.cfg:/etc/pretix/pretix.cfg:ro
      - pretix-data:/data
      - /etc/pretix:/etc/pretix
volumes:
  pretalx-db:
  pretalx-data:
  pretalx-redis:

  pretix-data:
  pretix-db:
  pretix-redis:

